# Generated by Django 5.1.5 on 2025-06-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
