# Generated by Django 5.1.5 on 2025-07-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default='guest', max_length=100),
        ),
    ]
