# Generated by Django 5.1.5 on 2025-07-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_cart_email_cart_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
